#ScenicView properties
#Wed Jun 24 17:59:50 CEST 2020
stageWidth=800.0
showBaseline=false
ignoreMouseTransparentNodes=true
splitPaneDividerPosition=0.32334183673469385
showNodesIdInTree=false
showDefaultProperties=true
showCSSProperties=false
showSearchBar=true
collapseControls=true
showFilteredNodesInTree=true
autoRefreshStyleSheets=false
showBounds=true
collapseContainerControls=false
automaticScenegraphStructureRefreshing=false
registerShortcuts=true
stageHeight=800.0
showInvisibleNodes=false
