package de.vw.paso.pll.dev.contextvisualizer.veron;

public enum VeronFields {
  Stuecklisten_ID,
  ZSB_ID,
  Teilenummer,
  Bezeichnung1,
  Bezeichnung2,
  Verwendungsstelle,
  Umfang,
  Takt,
  Ebene,
  ZSB,
  Anzahl,
  Mengeneinheit,
  Gewichtssteuerkennzeichen,
  Berechnet_FE,
  Gewogen_FE,
  Geschaetzt_FE,
  Gewogen_Prod,
  PR_Nummer,
  Wahlweise_Kennzeichen,
  Typenkopf,
  Typenkopf_Kennzeichen,
  Aggregat,
  Einsatzdatum,
  Entfalldatum,
  Einsatzterminschluessel,
  Entfallterminschluessel,
  Entwicklungsstand_Datum,
  Entwicklungsstand_Kennzeichen,
  Zeichnungsdatum,
  Konstruktionsstand,
  Konstruktionsverantwortung,
  Konstruktionsgruppe,
  Werksplanung_Nutzer,
  Werksplanung_Lieferer,
  Modulkennzeichen,
  Abwicklungsschluessel,
  Recyclebar,
  Grundstoff,
  Qualitaet,
  ZSB_Kennzeichen,
  Set_Kennzeichen,
  Kontengruppe,
  Produktstruktur,
  Bezeichnung1_US,
  Bezeichnung2_US,
  Bezeichnung1_portugiesisch,
  Bezeichnung2_portugiesisch,
  Bezeichnung1_spanisch,
  Bezeichnung2_spanisch,
  Werkstoffinfo,
  WAK,
  Bearbeitungsstatus,
  Bearbeitungsbemerkung,
  Werkstoffrelevante_Bauteile,
  Vornummer,
  Mittelgruppe,
  Endnummer,
  Index,
  MEE,
  Zeichnungsdatum2,
  Zeichnungsstatus,
  Konstruktionsverantwortung1,
  Konstruktionsverantwortung2,
  Kostengruppe,
  NODE_ID,
  BAUKASTEN_NODE_ID,
  BAUKASTEN_ST,
  BAUKASTEN_KZ,
  TEILENUMMER_PARENT,
  NODE_TYPE,
  PROD,
  SORT_,
  Wahlweise_Fall,
  Wahlweise_Nummer;

  public String get(String[] data) {
    if (data.length <= ordinal()) {
      return null;
    } else {
      return data[ordinal()];
    }
  }
}
