sonar.projectKey=PASO:BACKEND
sonar.sourceEncoding = UTF-8
sonar.sources=/src/main/java
sonar.java.binaries = **/build/classes
sonar.scm.exclusions.disabled=true
sonar.java.libraries = /appl/gradle/build_cache/**/*.jar,build/libs/**/*.jar
sonar.exclusions = src/test/**, **/model/**, **/exceptions/**, **/user/model/**, **/user/repository/**, src/main/resources/**, **/*DTO.*
sonar.coverage.jacoco.xmlReportPaths = paso-server/build/jacoco/test/jacocoTestReport.xml
